### ISSUE TITLE
:UTRun tests/test.vim runs multiple test scripts

### ISSUE THREAD

**Issue by still-dreaming-1** [LucHermitte/vim-UT#2]
With one of my plugins I am only just starting to add tests. As a result, my only test resides in a tests/test.vim. When I run :UTRun tests/test.vim, it also runs a test from a completely different plugin. Apparently that plugin also has a tests/test.vim. The strange thing is, I started vim in the directory of my plugin, so :UTRun is finding a test from a completely unrelated directory, it is not even a subdirectory.

My plugin resides here:

`/home/jesse/.config/nvim/plugged/vim-project-tags`

The other plugin resisdes here:

`/home/jesse/.config/nvim/plugged/conque-term`

The tests directories are in those directories. Is `:UTRun` supposed to be looking in that other directory for tests? It doesn't seem right to me.

**Comment by LucHermitte** [comment]
Hi. Sorry for the delay.
For far, `:UTRun` was expected to look into `'runtime'`. I've just deprecated this.

**Comment by still-dreaming-1** [comment]
Working great now! Thanks.
