### ISSUE TITLE
:UTRun % runs tests twice

### ISSUE THREAD

**Issue by still-dreaming-1** [LucHermitte/vim-UT#3]
When I have a test file open, and I run `:UTRun %`, the results show up twice in the quickfix window, as if the tests ran twice.

**Comment by LucHermitte** [comment]
It's possible it's related to the fact your current directory is in your runtime path.
It should be fixed with next release.
Let me know if it's not.

**Comment by still-dreaming-1** [comment]
Thanks! I will try it out.

**Comment by still-dreaming-1** [comment]
It is working now :D
