### ISSUE TITLE
Feature Request: Different color for number of tests passing

### ISSUE THREAD

**Issue by still-dreaming-1** [LucHermitte/vim-UT#4]
When using `:UTRun`, it would be nice if the number of passing tests was a different color so it would stand out from the rest of the text. This would help the user to quickly visually process if the tests passed. Maybe the numbers could be green if they all passed and red if some failed. Not sure if there is a good way to do that in the quickfix...

**Comment by LucHermitte** [comment]
Yes it can be done.
Let me now if these colours are fine for you.

**Comment by still-dreaming-1** [comment]
That is awesome! Love it!
