### ISSUE TITLE
Feature request: :UTRun support recursive glob

### ISSUE THREAD

**Issue by still-dreaming-1** [LucHermitte/vim-UT#5]
It would be nice to be able to run something like `:UTRun **test.vim` and have that glob pattern search subdirectories as well.

**Comment by LucHermitte** [comment]
Have you tried `:UTRun **/test.vim`? It should work normally.

**Comment by still-dreaming-1** [comment]
Yeah, it didn't seem to work for me.

**Comment by LucHermitte** [comment]
That's odd.
Internally, I do a `globpath('.', the_pattern)`. The fact that `**test.vim` doesn't work is normal, but not `**/test.vim` (if you have files exactly named `test.vim`), or `**/*test.vim` (for `foo/bartest.vim`, `bar/foo/tititest.vim`, ....)

**Comment by still-dreaming-1** [comment]
Oh, nevermind that works. I didn't notice the slash. Strange it still matches files that way that are not inside a sub directory. Thank you, that does exactly what I wanted.

**Comment by LucHermitte** [comment]
OK.
Thanks.
